### ISSUE TITLE
Robots.txt

### ISSUE THREAD

**Issue by lhassell** [audiobookshelf/audiobookshelf-web#106]
Question: Is it possible to insert a robots.txt file to forbid search crawling for those of us running on a FQDN?

**Comment by nichwall** [comment]
This repo is specific to the ABS website hosted at audiobookshelf.org

The repo for the server and web client is here: https://github.com/advplyr/audiobookshelf

**Comment by advplyr** [comment]
The ABS web client has a robots.txt
