### ISSUE TITLE
[Bug] Discord invitation link is invalid across all sources

### ISSUE THREAD

**Issue by mikehoyle** [audiobookshelf/audiobookshelf-web#76]
Repro steps:

1. Visit https://www.audiobookshelf.org/support/ and click "Discord server" link.
2. Get directed to https://discord.com/invite/HQgCbd6E75, which displays an "Invalid Invite" display.

Alternatively, attempt to access the discord server from the advplyr/audiobookshelf Bug report GitHub page and see the same result.

**Comment by advplyr** [comment]
I'm not getting this issue. Since you posted this about 10 users have joined from that invite link. Maybe you had a temp issue?

**Comment by mikehoyle** [comment]
Huh, I repro'ed multiple times last evening, but successfully used the link today. Sorry for the noise, closing.
